#!/usr/bin/env bash
# install-kimi-hooks.sh — bootstrap Kimi CLI (Moonshot AI) hooks from
# the canonical template.
#
# Kimi CLI uses a TOML config at `~/.kimi/config.toml` with a flat
# array of [[hooks]] blocks. Per-block fields: `event`, `matcher`
# (regex, optional), `command`, `timeout` (seconds).
#
# Schema reference: github.com/MoonshotAI/kimi-cli (docs/en/customization/hooks.md).
#
# Translation from Claude:
#   Events: PreToolUse / PostToolUse / Stop preserved verbatim (Kimi
#           uses the same PascalCase naming).
#   Matchers: Bash → RunShell, Write → WriteFile, Edit → StrReplaceFile.
#   Timeout: seconds (same as Claude).
#
# Output is TOML, not JSON. Each Claude (event, matcher, command-tuple)
# becomes one [[hooks]] block. The translation produces multiple blocks
# per event/matcher pair when Claude has multiple hooks under a single
# matcher (one block per command).
#
# Default config location is user-level (~/.kimi/config.toml) per the
# upstream docs. Pass --project to use .kimi/config.toml in the project
# root instead (experimental; Kimi may not read project-level config).
#
# Usage:
#   bash skills/autonomous-common/scripts/install-kimi-hooks.sh
#   bash skills/autonomous-common/scripts/install-kimi-hooks.sh --project
#
# Idempotent. --no-git-hook to skip the per-worktree git pre-push (#65).

set -euo pipefail

INSTALL_GIT_HOOK=1
USE_PROJECT_LEVEL=0
for arg in "$@"; do
  case "$arg" in
    --no-git-hook) INSTALL_GIT_HOOK=0 ;;
    --project) USE_PROJECT_LEVEL=1 ;;
    -h|--help)
      sed -n '2,/^$/p' "$0" | sed 's/^# \?//'
      exit 0
      ;;
    *) echo "Unknown argument: $arg" >&2; exit 2 ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"

# shellcheck source=lib-installer.sh
source "$SCRIPT_DIR/lib-installer.sh"
# shellcheck source=lib-installer-translate.sh
source "$SCRIPT_DIR/lib-installer-translate.sh"

require_jq

TEMPLATE="$SCRIPT_DIR/claude-settings.template.json"
if [[ ! -f "$TEMPLATE" ]]; then
  echo "ERROR: canonical template not found at: $TEMPLATE" >&2
  exit 1
fi

if (( USE_PROJECT_LEVEL == 1 )); then
  target="$(project_root)/.kimi/config.toml"
else
  : "${HOME:?HOME must be set for user-level Kimi config}"
  target="$HOME/.kimi/config.toml"
fi

# Translate Claude → Kimi tool names (events stay as PascalCase).
AGENT_EVENT_MAP="PreToolUse:PreToolUse PostToolUse:PostToolUse Stop:Stop"
AGENT_TOOL_MAP="Bash:RunShell Write:WriteFile Edit:StrReplaceFile"
export AGENT_EVENT_MAP AGENT_TOOL_MAP

# translate_template_hooks gives us the same { event: [{matcher,
# hooks: [...]}] } shape as Claude. We need to flatten that into
# [[hooks]] TOML blocks (one per individual command).
translated=$(translate_template_hooks "$TEMPLATE")

# Emit TOML. Format:
#   # autogenerated header
#   [[hooks]]
#   event = "..."
#   matcher = "..."   # omitted if entry has no matcher
#   command = "..."
#   timeout = N
#
# JSON-string escaping in TOML strings: " -> \", \ -> \\, newline -> \n.
# Our hook commands are simple shell paths so the only realistic char to
# escape is "; we use jq's @json filter to produce safe TOML strings
# (TOML basic strings are JSON-string compatible for our subset).

emit_toml() {
  local hooks_json="$1"

  # Header
  cat <<EOF
# Autogenerated by install-kimi-hooks.sh from
# skills/autonomous-common/scripts/claude-settings.template.json.
# Edits inside [[hooks]] blocks will be overwritten on next install.
# Other top-level TOML keys are preserved through the merge step
# (see "merge with existing user TOML" below).

EOF

  # Stream the [[hooks]] blocks out via jq. For each event, for each
  # entry, for each command in entry.hooks: emit one [[hooks]] block.
  jq -r '
    to_entries[] |
    .key as $event |
    .value[] |
    (.matcher // "") as $matcher |
    .hooks[] |
    (
      "[[hooks]]",
      "event = \"\($event)\"",
      (if $matcher == "" then empty else "matcher = \"\($matcher)\"" end),
      "command = \(.command | @json)",
      "timeout = \(.timeout)",
      ""
    )
  ' <<<"$hooks_json"
}

# Compose the new TOML body (managed annotations as TOML comments;
# Kimi doesn't read top-level metadata fields the way settings.json
# files do).
managed_by=$(jq -r '._managed_by' "$TEMPLATE")
managed_note=$(jq -r '._managed_note' "$TEMPLATE")
toml_body=$(
  printf '# %s = "%s"\n' "_managed_by" "$managed_by"
  printf '# %s\n' "_managed_note: $managed_note"
  printf '\n'
  emit_toml "$translated"
)

mkdir -p "$(dirname "$target")"

# Strategy:
#   - File doesn't exist → write our TOML body verbatim.
#   - File exists →
#       Strip out any existing [[hooks]] blocks AND the managed_by /
#       managed_note comments AND surrounding blank lines.
#       Append our fresh hooks block to whatever's left.
#     This preserves the user's other TOML (like Codex's [features]
#     codex_hooks = true if they happen to put it in the same file —
#     they shouldn't, but we don't break them).

if [[ ! -f "$target" ]]; then
  printf '%s' "$toml_body" > "$target"
  echo "Created: $target" >&2
else
  backup="$(backup_path "$target")"
  cp "$target" "$backup"

  # Remove old [[hooks]] blocks: each block is `[[hooks]]` followed by
  # contiguous `key = value` lines until the next blank line or [[/[ header.
  # Use awk to strip them.
  tmp=$(mktemp)
  # shellcheck disable=SC2064  # want $tmp expanded NOW
  trap "rm -f '$tmp'" EXIT
  awk '
    BEGIN { in_hooks = 0; in_managed_block = 0; in_autogen_header = 0 }

    # Strip the managed-by comment line, the _managed_note line, and any
    # contiguous comment lines until a blank line. This gracefully handles
    # both the "old" 2-line form and a future "_managed_note: ..." that
    # spans more than one line.
    /^# _managed_by = / { in_managed_block = 1; next }
    in_managed_block {
      if (/^[[:space:]]*$/)   { in_managed_block = 0; next }
      if (/^#/)               { next }
      in_managed_block = 0  # fall through to regular processing
    }

    # Strip the autogenerated header block: starts at
    # "# Autogenerated by install-kimi-hooks.sh" and runs through the
    # contiguous comment lines until the next blank line. Without this,
    # each re-install accumulates the prior header at the top of the file.
    /^# Autogenerated by install-kimi-hooks\.sh/ { in_autogen_header = 1; next }
    in_autogen_header {
      if (/^[[:space:]]*$/)   { in_autogen_header = 0; next }
      if (/^#/)               { next }
      in_autogen_header = 0
    }

    # Detect start of a [[hooks]] block.
    /^\[\[hooks\]\][[:space:]]*$/ { in_hooks = 1; next }
    # Inside a [[hooks]] block: skip key=value lines and blank lines.
    in_hooks {
      if (/^[[:space:]]*$/)     { in_hooks = 0; next }   # block ends at blank line
      if (/^[[:space:]]*\[/)    { in_hooks = 0; print; next }  # next table/array
      next
    }
    { print }
  ' "$target" > "$tmp"

  # Append fresh hooks body. Add a separator newline if existing content
  # didn't end with one.
  if [[ -s "$tmp" ]] && [[ $(tail -c 1 "$tmp" | wc -l) -eq 0 ]]; then
    printf '\n' >> "$tmp"
  fi
  printf '%s' "$toml_body" >> "$tmp"

  mv "$tmp" "$target"
  trap - EXIT
  echo "Updated: $target (backup at $backup)" >&2
fi

if (( INSTALL_GIT_HOOK == 1 )); then
  install_per_worktree_pre_push
fi

cat <<EOF >&2

NOTE: Kimi CLI hooks are beta upstream. Tool-name matchers
(RunShell, WriteFile, StrReplaceFile) are based on the documented
list at github.com/MoonshotAI/kimi-cli — verify your first hook
fires before relying on them.

Wrote to: $target
$( (( USE_PROJECT_LEVEL == 1 )) && echo "(project-level — experimental, Kimi may only read user-level)" )

EOF
echo "Done. Kimi hooks installed at $target." >&2
